# Generated by Django 5.2.3 on 2025-06-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='academic_track',
            field=models.CharField(blank=True, choices=[('general', 'عام (الصف الأول الثانوي)'), ('scientific_sec_2', 'علمي (الصف الثاني الثانوي)'), ('literary_sec_2', 'أدبي (الصف الثاني الثانوي)'), ('science_sec_3', 'علمي علوم (الصف الثالث الثانوي)'), ('math_sec_3', 'علمي رياضة (الصف الثالث الثانوي)'), ('literary_sec_3', 'أدبي (الصف الثالث الثانوي)')], max_length=50, null=True, verbose_name='المسار الدراسي'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='category_type',
            field=models.CharField(blank=True, choices=[('arabic_lang', 'اللغة العربية'), ('foreign_lang_1', 'اللغة الأجنبية الأولى'), ('history', 'التاريخ'), ('math', 'الرياضيات'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'الأحياء'), ('philosophy_logic', 'الفلسفة والمنطق'), ('religious_edu', 'التربية الدينية'), ('foreign_lang_2', 'اللغة الأجنبية الثانية'), ('programming_cs', 'البرمجة وعلوم الحاسب'), ('eg_national_edu', 'EG التربية الوطنية'), ('vocational_edu', 'التربية المهنية'), ('military_edu', 'التربية العسكرية'), ('psychology', 'علم النفس'), ('business_admin', 'إدارة أعمال'), ('accounting', 'المحاسبة'), ('geology', 'الجيولوجيا')], max_length=50, null=True, verbose_name='الفئة المطلوبة (للأستاذ)'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='what_will_you_add',
            field=models.TextField(blank=True, null=True, verbose_name='ما الذي ستضيفه للمنصة؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم الأخير'),
        ),
    ]
