# Generated by Django 5.2.3 on 2025-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountrequest_academic_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(blank=True, choices=[('cairo', 'القاهرة'), ('alexandria', 'الإسكندرية'), ('giza', 'الجيزة'), ('qalyubia', 'القليوبية'), ('sharqia', 'الشرقية'), ('monufia', 'المنوفية'), ('beheira', 'البحيرة'), ('gharbia', 'الغربية'), ('kafr_el_sheikh', 'كفر الشيخ'), ('fayoum', 'الفيوم'), ('beni_suef', 'بني سويف'), ('minya', 'المنيا'), ('assiut', 'أسيوط'), ('sohag', 'سوهاج'), ('qena', 'قنا'), ('luxor', 'الأقصر'), ('aswan', 'أسوان'), ('red_sea', 'البحر الأحمر'), ('new_valley', 'الوادي الجديد'), ('matrouh', 'مطروح'), ('north_sinai', 'شمال سيناء'), ('south_sinai', 'جنوب سيناء'), ('suez', 'السويس'), ('ismailia', 'الإسماعيلية'), ('port_said', 'بورسعيد'), ('damietta', 'دمياط')], max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='category_type',
            field=models.CharField(blank=True, choices=[('arabic_lang', 'اللغة العربية'), ('english_lang', 'اللغة الإنجليزية'), ('french_lang', 'اللغة الفرنسية'), ('german_lang', 'اللغة الألمانية'), ('history', 'التاريخ'), ('math', 'الرياضيات'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'الأحياء'), ('philosophy_logic', 'الفلسفة والمنطق'), ('religious_edu', 'التربية الدينية'), ('programming_cs', 'البرمجة وعلوم الحاسب'), ('eg_national_edu', 'EG التربية الوطنية'), ('vocational_edu', 'التربية المهنية'), ('military_edu', 'التربية العسكرية'), ('psychology', 'علم النفس'), ('geography', 'الجغرافيا'), ('sociology', 'علم اجتماع'), ('geology', 'الجيولوجيا'), ('applied_math', 'الرياضيات التطبيقية'), ('solid_geometry', 'الهندسة الفراغية'), ('statistics', 'الإحصاء'), ('environmental_science', 'علوم البيئة'), ('economy', 'الاقتصاد'), ('philosophy', 'فلسفة'), ('logic', 'منطق'), ('civics', 'المواطنة')], max_length=50, null=True, verbose_name='الفئة المطلوبة (للأستاذ)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'أستاذ'), ('team_member', 'عضو فريق عمل'), ('admin', 'مسؤول')], default='student', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
