# Generated by Django 5.2.3 on 2025-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_gender_customuser_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialized_subject',
            field=models.CharField(blank=True, choices=[('arabic_lang', 'اللغة العربية'), ('english_lang', 'اللغة الإنجليزية'), ('french_lang', 'اللغة الفرنسية'), ('german_lang', 'اللغة الألمانية'), ('history', 'التاريخ'), ('math', 'الرياضيات'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'الأحياء'), ('philosophy_logic', 'الفلسفة والمنطق'), ('religious_edu', 'التربية الدينية'), ('programming_cs', 'البرمجة وعلوم الحاسب'), ('eg_national_edu', 'EG التربية الوطنية'), ('vocational_edu', 'التربية المهنية'), ('military_edu', 'التربية العسكرية'), ('psychology', 'علم النفس'), ('geography', 'الجغرافيا'), ('sociology', 'علم اجتماع'), ('geology', 'الجيولوجيا'), ('applied_math', 'الرياضيات التطبيقية'), ('solid_geometry', 'الهندسة الفراغية'), ('statistics', 'الإحصاء'), ('environmental_science', 'علوم البيئة'), ('economy', 'الاقتصاد'), ('philosophy', 'فلسفة'), ('logic', 'منطق'), ('civics', 'المواطنة')], max_length=50, null=True, verbose_name='المادة المتخصصة'),
        ),
    ]
