# Generated by Django 5.0.6 on 2025-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_customuser_specialized_subject'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='academic_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='academic_track',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المسار الدراسي'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='category_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الفئة المطلوبة (للأستاذ)'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='job_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوظيفة المطلوبة (لفريق العمل)'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='parent_profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مهنة ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialized_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المادة المتخصصة'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
