# Generated by Django 5.2.3 on 2025-06-15 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكورس')),
                ('description', models.TextField(verbose_name='وصف الكورس التفصيلي')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الكورس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='صورة الكورس')),
                ('academic_level', models.CharField(choices=[('first_secondary', 'الصف الأول الثانوي'), ('second_secondary', 'الصف الثاني الثانوي'), ('third_secondary', 'الصف الثالث الثانوي')], max_length=50, verbose_name='الصف الدراسي')),
                ('academic_track', models.CharField(blank=True, choices=[('general', 'عام (الصف الأول الثانوي)'), ('scientific_sec_2', 'علمي (الصف الثاني الثانوي)'), ('literary_sec_2', 'أدبي (الصف الثاني الثانوي)'), ('science_sec_3', 'علمي علوم (الصف الثالث الثانوي)'), ('math_sec_3', 'علمي رياضة (الصف الثالث الثانوي)'), ('literary_sec_3', 'أدبي (الصف الثالث الثانوي)')], max_length=50, null=True, verbose_name='المسار الدراسي')),
                ('subject', models.CharField(choices=[('arabic_lang', 'اللغة العربية'), ('foreign_lang_1', 'اللغة الأجنبية الأولى'), ('history', 'التاريخ'), ('math', 'الرياضيات'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'الأحياء'), ('philosophy_logic', 'الفلسفة والمنطق'), ('religious_edu', 'التربية الدينية'), ('foreign_lang_2', 'اللغة الأجنبية الثانية'), ('programming_cs', 'البرمجة وعلوم الحاسب'), ('eg_national_edu', 'EG التربية الوطنية'), ('vocational_edu', 'التربية المهنية'), ('military_edu', 'التربية العسكرية'), ('psychology', 'علم النفس'), ('business_admin', 'إدارة أعمال'), ('accounting', 'المحاسبة'), ('geology', 'الجيولوجيا')], max_length=50, verbose_name='المادة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'كورسات',
                'unique_together': {('academic_level', 'academic_track', 'subject', 'teacher')},
            },
        ),
    ]
