# Generated by Django 5.0.6 on 2025-06-22 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='النقاط')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكورس')),
                ('description', models.TextField(verbose_name='وصف الكورس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الكورس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='صورة الكورس')),
                ('academic_level', models.CharField(choices=[('level_sec_1', 'الصف الأول الثانوي'), ('level_sec_2', 'الصف الثاني الثانوي'), ('level_sec_3', 'الصف الثالث الثانوي')], max_length=50, verbose_name='الصف الدراسي')),
                ('subject', models.CharField(choices=[('arabic', 'اللغة العربية'), ('english', 'اللغة الإنجليزية'), ('math_sec', 'الرياضيات (ثانوي عام)'), ('math_3_science', 'الرياضيات (علمي رياضة)'), ('math_3_lit', 'الرياضيات (أدبي)'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'الأحياء'), ('geology', 'الجيولوجيا'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('philosophy_logic', 'الفلسفة والمنطق'), ('philosophy_3', 'الفلسفة والمنطق (ثانوية عامة)'), ('religious_edu', 'التربية الدينية'), ('programming_cs', 'البرمجة وعلوم الحاسب'), ('eg_national_edu', 'التربية الوطنية'), ('vocational_edu', 'التربية المهنية'), ('military_edu', 'التربية العسكرية'), ('psychology', 'علم النفس'), ('sociology', 'علم اجتماع'), ('applied_math', 'الرياضيات التطبيقية'), ('solid_geometry', 'الهندسة الفراغية'), ('statistics', 'الإحصاء'), ('environmental_science', 'علوم البيئة'), ('economy', 'الاقتصاد'), ('philosophy', 'فلسفة'), ('logic', 'منطق'), ('civics', 'المواطنة')], max_length=50, verbose_name='المادة')),
                ('course_type', models.CharField(choices=[('regular', 'كورس عادي'), ('separate', 'كورس منفصل (مراجعة/برنامج خاص)')], default='regular', max_length=20, verbose_name='نوع الكورس')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'كورسات',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المحاضرة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المحاضرة')),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشورة')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفلة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course', verbose_name='الكورس')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'محاضرات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المادة')),
                ('type', models.CharField(choices=[('video', 'فيديو شرح'), ('pdf', 'ملف PDF'), ('quiz', 'واجب'), ('exam', 'امتحان'), ('link', 'رابط خارجي'), ('text', 'نص/شرح'), ('branch', 'فرع')], max_length=20, verbose_name='نوع المادة')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='ملف')),
                ('url', models.URLField(blank=True, null=True, verbose_name='رابط خارجي')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='محتوى نصي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشورة')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lecture', verbose_name='المحاضرة')),
            ],
            options={
                'verbose_name': 'مادة تعليمية',
                'verbose_name_plural': 'مواد تعليمية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'خيارات',
            },
        ),
        migrations.CreateModel(
            name='QuizOrAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الاختبار (بالدقائق)')),
                ('passing_score_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='نسبة النجاح المطلوبة (%)')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_details', to='courses.material', verbose_name='المادة المرتبطة')),
            ],
            options={
                'verbose_name': 'واجب/امتحان',
                'verbose_name_plural': 'واجبات/امتحانات',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_or_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quizorassignment', verbose_name='الواجب/الامتحان'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='required_quiz_or_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_lectures', to='courses.quizorassignment', verbose_name='الواجب/الامتحان المطلوب لفتح القفل'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('is_graded', models.BooleanField(default=False, verbose_name='تم التصحيح')),
                ('passed', models.BooleanField(default=False, verbose_name='اجتاز')),
                ('quiz_or_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.quizorassignment', verbose_name='الواجب/الامتحان')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقديم واجب/امتحان',
                'verbose_name_plural': 'تقديمات الواجبات/الامتحانات',
                'unique_together': {('quiz_or_assignment', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('course', 'order')},
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='إجابة نصية (إذا لم تكن خيارات)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('chosen_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.choice', verbose_name='الخيار المختار')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='السؤال')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.submission', verbose_name='التقديم')),
            ],
            options={
                'verbose_name': 'إجابة طالب',
                'verbose_name_plural': 'إجابات الطلاب',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
