# Generated by Django 5.2.3 on 2025-06-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='الدرجة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('video', 'فيديو'), ('pdf', 'ملف PDF'), ('quiz', 'واجب'), ('exam', 'امتحان'), ('link', 'رابط خارجي'), ('text', 'نص/شرح'), ('branch', 'فرع رئيسي')], max_length=20, verbose_name='نوع المادة'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل هو الإجابة الصحيحة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار إجابة',
                'verbose_name_plural': 'خيارات الإجابة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizOrAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('quiz', 'اختبار'), ('assignment', 'واجب')], max_length=20, verbose_name='النوع')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='مدة الاختبار بالدقائق')),
                ('passing_score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة النجاح المطلوبة (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_assignments', to='courses.lecture', verbose_name='المحاضرة')),
            ],
            options={
                'verbose_name': 'اختبار/واجب',
                'verbose_name_plural': 'اختبارات/واجبات',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_or_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quizorassignment', verbose_name='الاختبار/الواجب'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('is_passed', models.BooleanField(default=False, verbose_name='هل تم الاجتياز؟')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('quiz_or_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.quizorassignment', verbose_name='الاختبار/الواجب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسليم',
                'verbose_name_plural': 'تسليمات',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz_or_assignment', 'order')},
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هل الإجابة صحيحة؟')),
                ('chosen_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.choice', verbose_name='الخيار المختار')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='السؤال')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.submission', verbose_name='التسليم')),
            ],
            options={
                'verbose_name': 'إجابة طالب',
                'verbose_name_plural': 'إجابات الطلاب',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
