# Generated by Django 5.2.3 on 2025-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question_alter_material_type_choice_quizorassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'كورس عادي'), ('separate', 'كورس منفصل')], default='regular', max_length=20, verbose_name='نوع الكورس'),
        ),
    ]
