# Generated by Django 5.0.6 on 2025-06-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_unique_together_alter_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='مقفلة وتتطلب إكمال واجب/امتحان سابق؟'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='required_quiz_or_exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locks_lecture', to='courses.quizorassignment', verbose_name='الواجب/الامتحان المطلوب لفتح هذه المحاضرة'),
        ),
        migrations.AddField(
            model_name='material',
            name='quiz_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_link', to='courses.quizorassignment', verbose_name='الواجب/الامتحان المرتبط'),
        ),
        migrations.AlterField(
            model_name='quizorassignment',
            name='type',
            field=models.CharField(choices=[('quiz', 'واجب'), ('exam', 'امتحان')], max_length=20, verbose_name='النوع'),
        ),
    ]
